import { ICard } from '../models';

export const çcardWrapper: ICard = {
  cardId: 'empty',
  dbfId: 'empty',
  name: 'empty',
  cardSet: 'empty',
  type: 'empty',
  faction: 'empty',
  rarity: 'empty',
  cost: 0,
  attack: 0,
  health: 0,
  text: 'empty',
  flavor: 'empty',
  artist: 'empty',
  collectible: 0,
  elite: 0,
  race: 'empty',
  playerClass: 'empty',
  howToGet: 'empty',
  howToGetGold: 'empty',
  howToGetDiamond: 'empty',
  img: 'empty',
  imgGold: 'empty',
  locale: 'empty',
  mechanics: []
};

export const çcardIndexes = [
  'cardId',
  'dbfId',
  'name',
  'cardSet',
  'type',
  'faction',
  'rarity',
  'cost',
  'attack',
  'health',
  'text',
  'flavor',
  'artist',
  'collectible',
  'elite',
  'race',
  'playerClass',
  'howToGet',
  'howToGetGold',
  'howToGetDiamond',
  'img',
  'imgGold',
  'locale',
  'mechanics'
];
